version: "3.0"
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        PHP_VERSION: 7.4
    env_file: .env
    user: "$_UID:$_GID"
    volumes:
      - "./:$APP_SOURCE_ROOT"
      - "./docker/php-fpm/etc/php.ini:/usr/local/etc/php/php.ini"
    working_dir: "$APP_SOURCE_ROOT"
    depends_on:
      - postgres
    environment:
      - "PHP_IDE_CONFIG=serverName=Docker"

  nginx:
    image: "nginx:1.19.3-alpine"
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "./:$APP_SOURCE_ROOT"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "php-fpm"

  composer:
    env_file: .env
    user: "$_UID:$_GID"
    network_mode: "host"
    image: "composer:1.9.3"
    working_dir: "$APP_SOURCE_ROOT"
    environment:
      COMPOSER_HOME: "$COMPOSER_HOME"
      COMPOSER_CACHE_DIR: "$COMPOSER_CACHE_DIR"
    volumes:
      - "$COMPOSER_HOME:$COMPOSER_HOME"
      - "$COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR"
      - "./:$APP_SOURCE_ROOT"
    command: "composer install"

  postgres:
    image: "postgres:12-alpine"
    env_file: .env
    environment:
      - "POSTGRES_USER=$DB_USERNAME"
      - "POSTGRES_PASSWORD=$DB_PASSWORD"
      - "POSTGRES_DB=$DB_DATABASE"
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data

